### ISSUE TITLE
ios-sim doesn't launch iOS 8 simulator on Jenkins server

### ISSUE THREAD

**Issue by urklc** [phonegap/ios-sim#129]
I have a Jenkins server setup and 2 admin users "jenkins" and "ugur".

Before XCode 6 supported version, I was successfully opening simulator with:
sudo -S su - ugur -c '/Users/ugur/Desktop/ios-sim launch /Users/ugur/Desktop/test.app'

But now it's giving this error and hangs:
Could not start simulator session: <iPhoneSimulator: 0x7f88d35075a0>

**Comment by shazron** [comment]
Try v4.x

**Comment by nemesis** [comment]
v4 works fine for me.
