### ISSUE TITLE
No console output from ios-sim

### ISSUE THREAD

**Issue by slavasav** [phonegap/ios-sim#134]
Trying to run ios-sim gives no stderr. I get output if redirect it via --stderr option though.
ios-sim --version
2.0.1
```
ios-sim  launch  App.app --devicetypeid "com.apple.CoreSimulator.SimDeviceType.iPhone-5" --sdk 8.1
<no output in console>
ios-sim  launch  App.app --devicetypeid "com.apple.CoreSimulator.SimDeviceType.iPhone-5" --sdk 8.1 --stderr err.log
cat err.log
2014-12-01 14:17:43.118 App[47029:396400] Using No-op implementation for PKPushRegistry
```

**Comment by archaeopterasa** [comment]
I see this issue also, but it goes away after the first time ios-sim has been run on a particular simulator. E.g.:
```
$ ios-sim launch App.app --devicetypeid "com.apple.CoreSimulator.SimDeviceType.iPhone-5"
<Simulator runs no output in console>
<Close simulator>
$ ios-sim launch App.app --devicetypeid "com.apple.CoreSimulator.SimDeviceType.iPhone-5"
<Normal output>
$ xcrun simctl erase "iPhone 5"
$ ios-sim launch App.app --devicetypeid "com.apple.CoreSimulator.SimDeviceType.iPhone-5"
<back to no output>
```

The failure happens on each device model independently until the simulator first runs on that configuration. This has been an issue for some of my automation, but I was glad to find this bug report since now that I know --stderr still works I can have my scripts do an extra pipe to work around it.

**Comment by archaeopterasa** [comment]
I dug into this a bit more and figured out the problem, it was trying to create symlinks to the stdout / stderr pipes before the containing directory existed on the fresh simulator. I just sent a pull request with the fix.

**Comment by slavasav** [comment]
Great, thank you! Slava04.01.2015, 06:38, "Andrea" <notifications@github.com>:I dug into this a bit more and figured out the problem, it was trying to create symlinks to the stdout / stderr pipes before the containing directory existed on the fresh simulator. I just sent a pull request with the fix.—Reply to this email directly or view it on GitHub.

**Comment by shazron** [comment]
#136 pulled in.

**Comment by shazron** [comment]
Re-opening until 3.2.0 is released
