### ISSUE TITLE
** BUILD FAILED ** npm -g install ios-sim on Mac OS X 10.7.5 (Lion).

### ISSUE THREAD

**Issue by flagsoft** [phonegap/ios-sim#140]
Just did:
sudo npm -g install ios-sim
on my machine, and it failed to build.

----
** BUILD FAILED **

The following build commands failed:
	CompileC build/ios-sim.build/Release/ios-sim.build/Objects-normal/i386/iPhoneSimulator.o Source/iPhoneSimulator.m normal i386 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
rake aborted!
Command failed with status (65): [xcodebuild -project ios-sim.xcodeproj -con...]
/usr/local/lib/node_modules/ios-sim/Rakefile:13
(See full trace by running task with --trace)

npm ERR! ios-sim@3.1.1 preinstall: `rake build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ios-sim@3.1.1 preinstall script.
npm ERR! This is most likely a problem with the ios-sim package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     rake build
npm ERR! You can get their info via:
npm ERR!     npm owner ls ios-sim
npm ERR! There is likely additional logging output above.
npm ERR! System Darwin 11.4.2
npm ERR! command "node" "/usr/local/bin/npm" "-g" "install" "ios-sim"
npm ERR! cwd /Volumes/DATA/Prj-TESTING/ionicframework/test01/myApp
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0
----

**Comment by flagsoft** [comment]
-------------
Type' is a C11 feature [-Wtypedef-redefinition]
typedef void (^CDUnknownBlockType)(void); // return type and parameters are unknown
               ^
/usr/local/lib/node_modules/ios-sim/DVTiPhoneSimulatorRemoteClient/../CoreSimulator/CoreSimulator.h:11:16: note: previous definition is here
typedef void (^CDUnknownBlockType)(void); // return type and parameters are unknown
               ^
/usr/local/lib/node_modules/ios-sim/Source/iPhoneSimulator.m:510:52: error: property 'firstObject' not found on object of type 'NSArray *'
                NSString* typeIdentifier = [deviceTypeAndVersion.firstObject stringByTrimmingCharactersInSet:[NSCharacterSet whitespaceCharacterSet]];
                                                                 ^
/usr/local/lib/node_modules/ios-sim/Source/iPhoneSimulator.m:135:20: error: returning 'NSArray' from a function with incompatible result type 'NSString *'
            return parts[1];
                   ^~~~~~~~
1 warning and 2 errors generated.

CompileC build/ios-sim.build/Release/ios-sim.build/Objects-normal/i386/main.o Source/main.m normal i386 objective-c com.apple.compilers.llvm.clang.1_0.compiler
    cd /usr/local/lib/node_modules/ios-sim
    setenv LANG en_US.US-ASCII
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -arch i386 -fmessage-length=0 -std=gnu99 -Wno-trigraphs -fpascal-strings -Os -Wno-missing-field-initializers -Wno-missing-prototypes -Wreturn-type -Wno-implicit-atomic-properties -Wno-receiver-is-weak -Wformat -Wno-missing-braces -Wparentheses -Wswitch -Wno-unused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wno-empty-body -Wno-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wno-constant-conversion -Wno-int-conversion -Wno-enum-conversion -Wno-shorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wno-undeclared-selector -Wno-deprecated-implementations -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk -fasm-blocks -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -mmacosx-version-min=10.7 -g -fvisibility=hidden -Wno-sign-conversion -iquote /usr/local/lib/node_modules/ios-sim/build/ios-sim.build/Release/ios-sim.build/ios-sim-generated-files.hmap -I/usr/local/lib/node_modules/ios-sim/build/ios-sim.build/Release/ios-sim.build/ios-sim-own-target-headers.hmap -I/usr/local/lib/node_modules/ios-sim/build/ios-sim.build/Release/ios-sim.build/ios-sim-all-target-headers.hmap -iquote /usr/local/lib/node_modules/ios-sim/build/ios-sim.build/Release/ios-sim.build/ios-sim-project-headers.hmap -I/usr/local/lib/node_modules/ios-sim/build/Release/include -I. -I/usr/local/lib/node_modules/ios-sim/build/ios-sim.build/Release/ios-sim.build/DerivedSources/i386 -I/usr/local/lib/node_modules/ios-sim/build/ios-sim.build/Release/ios-sim.build/DerivedSources -F/usr/local/lib/node_modules/ios-sim/build/Release -include /var/folders/zz/zyxvpxvq6csfxvn_ngzzzzzvzzzzzy/C/com.apple.Xcode.4294967294/SharedPrecompiledHeaders/ios-sim_Prefix-blxjhwwfvebfpoeluiqwqgppevtp/ios-sim_Prefix.pch -MMD -MT dependencies -MF /usr/local/lib/node_modules/ios-sim/build/ios-sim.build/Release/ios-sim.build/Objects-normal/i386/main.d --serialize-diagnostics /usr/local/lib/node_modules/ios-sim/build/ios-sim.build/Release/ios-sim.build/Objects-normal/i386/main.dia -c /usr/local/lib/node_modules/ios-sim/Source/main.m -o /usr/local/lib/node_modules/ios-sim/build/ios-sim.build/Release/ios-sim.build/Objects-normal/i386/main.o
In file included from /usr/local/lib/node_modules/ios-sim/Source/main.m:10:
In file included from /usr/local/lib/node_modules/ios-sim/Source/iPhoneSimulator.h:9:
/usr/local/lib/node_modules/ios-sim/DVTiPhoneSimulatorRemoteClient/DVTiPhoneSimulatorRemoteClient.h:11:16: warning: redefinition of typedef 'CDUnknownBlockType' is a C11 feature [-Wtypedef-redefinition]
typedef void (^CDUnknownBlockType)(void); // return type and parameters are unknown
               ^
/usr/local/lib/node_modules/ios-sim/DVTiPhoneSimulatorRemoteClient/../CoreSimulator/CoreSimulator.h:11:16: note: previous definition is here
typedef void (^CDUnknownBlockType)(void); // return type and parameters are unknown
               ^
1 warning generated.
-------------

**Comment by shazron** [comment]
Also provide the details required (the link was there when you filed):
https://github.com/phonegap/ios-sim/blob/master/CONTRIBUTING.md

**Comment by flagsoft** [comment]
?
This link is contributing to ios-sim...

On Wed, Feb 11, 2015 at 5:18 PM, Shazron Abdullah <notifications@github.com>
wrote:

> Also provide the details required (the link was there when you filed):
> https://github.com/phonegap/ios-sim/blob/master/CONTRIBUTING.md
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/phonegap/ios-sim/issues/140#issuecomment-73909878>.
>



-- 
Aktion: Artikel und Bücher zum günstigen Preis
https://www.exsila.ch/flag
http://www.anibis.ch/de/advertlist.aspx?sun=flag2

Freundliche Grüsse / Kind regards



*Michael Mustun*

**Comment by shazron** [comment]
Did you actually read the page? Filing an issue is contributing. Read it.

**Comment by flagsoft** [comment]
Sure, but the file name is misleading.

sw_vers -productVersion
10.7.5

ios-sim --version
-bash: ios-sim: command not found

xcodebuild -version
Xcode 4.6.3
Build version 4H1503

xcode-select --print-path
/Applications/Xcode.app/Contents/Developer



gcc --version
i686-apple-darwin11-llvm-gcc-4.2 (GCC) 4.2.1 (Based on Apple Inc. build 5658) (LLVM build 2336.11.00)
Copyright (C) 2007 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by flagsoft** [comment]
I just typed in:
$ sudo npm -g install ios-sim

So I just want to install ios-sim.

**Comment by shazron** [comment]
Thanks! The filename is mandated by Github so it picks it up automatically and displays it when someone files an issue.

From the diagnostic data, I can see your problem. ios-sim only supports Xcode 6 since version 3.0

**Comment by flagsoft** [comment]
Ok, hmm... there is nothing I can do about it, that it supports also older Xcode versions?

**Comment by shazron** [comment]
No.

**Comment by shazron** [comment]
Try the last 2.x version:
`npm install -g ios-sim@2.0.1`
