### ISSUE TITLE
ios-sim for Xcode 5.1

### ISSUE THREAD

**Issue by piclez** [phonegap/ios-sim#143]
Hi I'm still running non Yosemite OS so only Xcode 5.1 instead of 6 but I can't get the ios-sim to work with this setup. Should I downgrade to ios-sim 2.0.1 or other version compatible with Xcode 5.1?

Thanks,

Peter

**Comment by shazron** [comment]
Yes, v3.x only works with Xcode 6. Do a:
```npm install -g ios-sim@2.0.1```
