### ISSUE TITLE
unable to launch app

### ISSUE THREAD

**Issue by swapnilappsplanet** [phonegap/ios-sim#144]
I used ios-sim launch /swapnil/iphone\ workspace/fiindme/build/Release-iphonesimulator/fiindme.app --devicetypeid "com.apple.CoreSimulator.SimDeviceType.iPhone-5s, 8.1"

Session could not be started: Error Domain=LaunchServicesError Code=0 "Unable to run app in Simulator" UserInfo=0x7f885bf04ea0 {Error=ExecutableTwiddleFailed, ErrorDescription=Failed to chmod file:///Users/swapnildeshmukh/Library/Developer/CoreSimulator/Devices/E865AA1C-E780-4FC3-9E9F-641C6218098D/data/Library/Caches/com.apple.containermanagerd/Temp/Bundle/Application/E6FED2A0-24E8-4E32-9F7C-B247CB2D6EBA/fiindme.app/fiindme : No such file or directory, NSLocalizedFailureReason=An error was encountered while running (Domain = LaunchServicesError, Code = 0), NSUnderlyingError=0x7f885bf05c80 "The operation couldn’t be completed. (LaunchServicesError error 0.)", NSLocalizedDescription=Unable to run app in Simulator}

same issue for simulator iphone-6,5,5s

but i can install app using xcode directly also by creating ipa. I cross checked with path but it fails.

**Comment by shazron** [comment]
Please provide the information required from here: https://github.com/phonegap/ios-sim/blob/master/CONTRIBUTING.md

**Comment by shazron** [comment]
Re-open if this occurs after trying version 4.x
