### ISSUE TITLE
Unable to install ios-sim through npm

### ISSUE THREAD

**Issue by j1ng8n** [phonegap/ios-sim#146]
When I tried to install iOS-sim through npm for ionic project, it gave me an error below:
Please take a look. Thank you.

npm ERR! ios-sim@3.1.1 preinstall: `rake build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ios-sim@3.1.1 preinstall script 'rake build'.
npm ERR! This is most likely a problem with the ios-sim package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     rake build
npm ERR! You can get their info via:
npm ERR!     npm owner ls ios-sim
npm ERR! There is likely additional logging output above.

===============npm-debug.log content=======================

0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'install', '-g', 'ios-sim' ]
2 info using npm@2.7.5
3 info using node@v0.12.2
4 verbose node symlink /usr/local/bin/node
5 silly cache add args [ 'ios-sim', null ]
6 verbose cache add spec ios-sim
7 silly cache add parsed spec { raw: 'ios-sim',
7 silly cache add   scope: null,
7 silly cache add   name: 'ios-sim',
7 silly cache add   rawSpec: '',
7 silly cache add   spec: '*',
7 silly cache add   type: 'range' }
8 verbose addNamed ios-sim@*
9 silly addNamed semver.valid null
10 silly addNamed semver.validRange *
11 silly addNameRange { name: 'ios-sim', range: '*', hasData: false }
12 silly mapToRegistry name ios-sim
13 silly mapToRegistry using default registry
14 silly mapToRegistry registry https://registry.npmjs.org/
15 silly mapToRegistry uri https://registry.npmjs.org/ios-sim
16 verbose addNameRange registry:https://registry.npmjs.org/ios-sim not in flight; fetching
17 verbose request uri https://registry.npmjs.org/ios-sim
18 verbose request no auth needed
19 info attempt registry request try #1 at 16:34:03
20 verbose request id f0c9854853124556
21 verbose etag "LZQ64UFJSCLICI2NUYOLIGEP"
22 http request GET https://registry.npmjs.org/ios-sim
23 http 304 https://registry.npmjs.org/ios-sim
24 silly get cb [ 304,
24 silly get   { date: 'Mon, 20 Apr 2015 23:34:03 GMT',
24 silly get     server: 'Apache',
24 silly get     via: '1.1 varnish',
24 silly get     'last-modified': 'Mon, 20 Apr 2015 23:34:03 GMT',
24 silly get     'cache-control': 'max-age=60',
24 silly get     etag: '"LZQ64UFJSCLICI2NUYOLIGEP"',
24 silly get     age: '23',
24 silly get     'x-served-by': 'cache-lax1427-LAX',
24 silly get     'x-cache': 'HIT',
24 silly get     'x-cache-hits': '1',
24 silly get     'x-timer': 'S1429572843.369088,VS0,VE0',
24 silly get     vary: 'Accept',
24 silly get     'content-length': '0',
24 silly get     'keep-alive': 'timeout=10, max=50',
24 silly get     connection: 'Keep-Alive' } ]
25 verbose etag https://registry.npmjs.org/ios-sim from cache
26 verbose get saving ios-sim to /Users/F&H/.npm/registry.npmjs.org/ios-sim/.cache.json
27 silly addNameRange number 2 { name: 'ios-sim', range: '*', hasData: true }
28 silly addNameRange versions [ 'ios-sim',
28 silly addNameRange   [ '1.8.0',
28 silly addNameRange     '1.8.1',
28 silly addNameRange     '1.8.2',
28 silly addNameRange     '1.9.0',
28 silly addNameRange     '2.0.0',
28 silly addNameRange     '2.0.1',
28 silly addNameRange     '3.0.0',
28 silly addNameRange     '3.1.0',
28 silly addNameRange     '3.1.1',
28 silly addNameRange     '4.0.0',
28 silly addNameRange     '4.0.1' ] ]
29 verbose addNamed ios-sim@3.1.1
30 silly addNamed semver.valid 3.1.1
31 silly addNamed semver.validRange 3.1.1
32 silly cache afterAdd ios-sim@3.1.1
33 verbose afterAdd /Users/F&H/.npm/ios-sim/3.1.1/package/package.json not in flight; writing
34 verbose afterAdd /Users/F&H/.npm/ios-sim/3.1.1/package/package.json written
35 silly install resolved [ { name: 'ios-sim',
35 silly install resolved     version: '3.1.1',
35 silly install resolved     description: 'launch iOS apps into the iOS Simulator from the command line (Xcode 6.0)',
35 silly install resolved     main: 'ios-sim',
35 silly install resolved     scripts: { preinstall: 'rake build' },
35 silly install resolved     bin: { 'ios-sim': 'build/Release/ios-sim' },
35 silly install resolved     repository: { type: 'git', url: 'https://github.com/phonegap/ios-sim' },
35 silly install resolved     keywords: [ 'ios-sim', 'iOS Simulator' ],
35 silly install resolved     author: { name: 'Landon Fuller, Jeff Haynie, Eloy Duran, Shazron Abdullah' },
35 silly install resolved     license: 'MIT',
35 silly install resolved     gitHead: 'c6ec64397e5fa462f1ea2d4e4fdc123a856618f9',
35 silly install resolved     bugs: { url: 'https://github.com/phonegap/ios-sim/issues' },
35 silly install resolved     homepage: 'https://github.com/phonegap/ios-sim',
35 silly install resolved     _id: 'ios-sim@3.1.1',
35 silly install resolved     _shasum: '1129c3fda31b917ef656b8c53fd276392b51c6e8',
35 silly install resolved     _from: 'ios-sim@*',
35 silly install resolved     _npmVersion: '1.4.14',
35 silly install resolved     _npmUser: { name: 'shazron', email: 'shazron@gmail.com' },
35 silly install resolved     maintainers: [ [Object] ],
35 silly install resolved     dist:
35 silly install resolved      { shasum: '1129c3fda31b917ef656b8c53fd276392b51c6e8',
35 silly install resolved        tarball: 'http://registry.npmjs.org/ios-sim/-/ios-sim-3.1.1.tgz' },
35 silly install resolved     directories: {},
35 silly install resolved     _resolved: 'https://registry.npmjs.org/ios-sim/-/ios-sim-3.1.1.tgz',
35 silly install resolved     readme: 'ERROR: No README data found!' } ]
36 info install ios-sim@3.1.1 into /usr/local/lib
37 info installOne ios-sim@3.1.1
38 verbose installOne of ios-sim to /usr/local/lib not in flight; installing
39 verbose lock using /Users/F&H/.npm/_locks/ios-sim-3bb56db538048d2f.lock for /usr/local/lib/node_modules/ios-sim
40 silly install write writing ios-sim 3.1.1 to /usr/local/lib/node_modules/ios-sim
41 silly cache addNamed cb ios-sim@3.1.1
42 verbose unbuild lib/node_modules/ios-sim
43 silly gentlyRm /usr/local/lib/node_modules/ios-sim is being purged from base /usr/local
44 verbose gentlyRm don't care about contents; nuking /usr/local/lib/node_modules/ios-sim
45 verbose tar unpack /Users/F&H/.npm/ios-sim/3.1.1/package.tgz
46 verbose tar unpacking to /usr/local/lib/node_modules/ios-sim
47 silly gentlyRm /usr/local/lib/node_modules/ios-sim is being purged
48 verbose gentlyRm don't care about contents; nuking /usr/local/lib/node_modules/ios-sim
49 silly gunzTarPerm modes [ '755', '644' ]
50 silly gunzTarPerm extractEntry package.json
51 silly gunzTarPerm extractEntry .npmignore
52 silly gunzTarPerm extractEntry README.md
53 silly gunzTarPerm extractEntry LICENSE
54 silly gunzTarPerm extractEntry resources/buildbox/build.sh
55 silly gunzTarPerm extractEntry CoreSimulator/CoreSimulator.h
56 silly gunzTarPerm extractEntry CONTRIBUTING.md
57 silly gunzTarPerm extractEntry Rakefile
58 silly gunzTarPerm extractEntry Source/.npmignore
59 silly gunzTarPerm extractEntry Source/NSString+expandPath.h
60 silly gunzTarPerm extractEntry Source/NSString+expandPath.m
61 silly gunzTarPerm extractEntry Source/iPhoneSimulator.h
62 silly gunzTarPerm extractEntry Source/iPhoneSimulator.m
63 silly gunzTarPerm extractEntry Source/main.m
64 silly gunzTarPerm extractEntry Source/nsprintf.h
65 silly gunzTarPerm extractEntry Source/nsprintf.m
66 silly gunzTarPerm extractEntry Source/version.h
67 silly gunzTarPerm extractEntry ios-sim.xcodeproj/.npmignore
68 silly gunzTarPerm extractEntry ios-sim.xcodeproj/project.pbxproj
69 silly gunzTarPerm extractEntry ios-sim.xcodeproj/xcshareddata/xcschemes/ios-sim.xcscheme
70 silly gunzTarPerm extractEntry ios-sim_Prefix.pch
71 silly gunzTarPerm extractEntry DVTiPhoneSimulatorRemoteClient/DVTiPhoneSimulatorRemoteClient.h
72 silly gunzTarPerm extractEntry README.template.md
73 info preinstall ios-sim@3.1.1
74 verbose unsafe-perm in lifecycle false
75 info ios-sim@3.1.1 Failed to exec preinstall script
76 verbose unlock done using /Users/F&H/.npm/_locks/ios-sim-3bb56db538048d2f.lock for /usr/local/lib/node_modules/ios-sim
77 verbose stack Error: ios-sim@3.1.1 preinstall: `rake build`
77 verbose stack Exit status 1
77 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:213:16)
77 verbose stack     at EventEmitter.emit (events.js:110:17)
77 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:14:12)
77 verbose stack     at ChildProcess.emit (events.js:110:17)
77 verbose stack     at maybeClose (child_process.js:1015:16)
77 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
78 verbose pkgid ios-sim@3.1.1
79 verbose cwd /Users/F&H/Development/iApp/UNLVcheckInApp
80 error Darwin 14.3.0
81 error argv "node" "/usr/local/bin/npm" "install" "-g" "ios-sim"
82 error node v0.12.2
83 error npm  v2.7.5
84 error code ELIFECYCLE
85 error ios-sim@3.1.1 preinstall: `rake build`
85 error Exit status 1
86 error Failed at the ios-sim@3.1.1 preinstall script 'rake build'.
86 error This is most likely a problem with the ios-sim package,
86 error not with npm itself.
86 error Tell the author that this fails on your system:
86 error     rake build
86 error You can get their info via:
86 error     npm owner ls ios-sim
86 error There is likely additional logging output above.
87 verbose exit [ 1, true ]
88 verbose unbuild lib/node_modules/ios-sim
89 info preuninstall ios-sim@3.1.1
90 info uninstall ios-sim@3.1.1
91 verbose unbuild rmStuff ios-sim@3.1.1 from /usr/local/lib/node_modules
92 silly gentlyRm /usr/local/bin/ios-sim is being gently removed
93 silly gentlyRm verifying /usr/local is an npm working directory
94 silly gentlyRm containing path /usr/local is under npm's control, in /usr/local
95 silly gentlyRm deletion target /usr/local/bin/ios-sim is under /usr/local
96 verbose gentlyRm vacuuming from /usr/local/bin/ios-sim up to /usr/local
97 info postuninstall ios-sim@3.1.1
98 silly gentlyRm /usr/local/lib/node_modules/ios-sim is being purged from base /usr/local
99 verbose gentlyRm don't care about contents; nuking /usr/local/lib/node_modules/ios-sim
100 silly vacuum-fs purging /usr/local/lib/node_modules/ios-sim
101 silly vacuum-fs quitting because other entries in /usr/local/lib/node_modules

**Comment by shazron** [comment]
You forgot to follow the instructions https://github.com/phonegap/ios-sim/blob/master/CONTRIBUTING.md that was linked when you attempted to file the issue. Please provide the info.

**Comment by j1ng8n** [comment]
nvm, i can install it after:
$ brew update
$ brew upgrade node
$ npm cache clear
$ npm install ios-sim -g
