### ISSUE TITLE
ios-sim failed to start due to "launch path not accessible"

### ISSUE THREAD

**Issue by illusionhunter** [phonegap/ios-sim#147]
I installed ios-sim with "sudo npm install -g ios-sim" and everything seemed green, no errors, build was successful.

** BUILD SUCCEEDED **

/usr/local/bin/ios-sim -> /usr/local/lib/node_modules/ios-sim/build/Release/ios-sim
ios-sim@3.1.1 /usr/local/lib/node_modules/ios-sim

However, ios-sim cannot start:
```
ios-sim start
2015-05-11 18:59:21.380 ios-sim[28334:403429] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'launch path not accessible'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff900fc03c __exceptionPreprocess + 172
	1   libobjc.A.dylib                     0x00007fff8bc8376e objc_exception_throw + 43
	2   CoreFoundation                      0x00007fff900fbeed +[NSException raise:format:] + 205
	3   Foundation                          0x00007fff90cb114c -[NSConcreteTask launchWithDictionary:] + 444
	4   ios-sim                             0x00000001017eb714 GetXcodeVersion + 188
	5   ios-sim                             0x00000001017ed25b -[iPhoneSimulator runWithArgc:argv:] + 57
	6   ios-sim                             0x00000001017edfcb main + 101
	7   ios-sim                             0x00000001017eb3dc start + 52
	8   ???                                 0x0000000000000002 0x0 + 2
)
libc++abi.dylib: terminating with uncaught exception of type NSException
Abort
```
I'm on Yosemite 10.10.3, Xcode 6.3.1 with CLT. Cordova 3.6.3-0.2.13

**Comment by shazron** [comment]
Hi,
Please provide the other info required here: https://github.com/phonegap/ios-sim/blob/master/CONTRIBUTING.md

**Comment by illusionhunter** [comment]
sw_vers -productVersion
10.10.3

ios-sim --version
Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'launch path not accessible'
( from npm install we can see it's 3.1.1 )

xcodebuild -version
Xcode 6.3.1
Build version 6D1002

xcode-select -p
/Applications/Xcode.app/Contents/Developer

gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 6.1.0 (clang-602.0.49) (based on LLVM 3.6.0svn)
Target: x86_64-apple-darwin14.3.0
Thread model: posix

**Comment by illusionhunter** [comment]
Same version of ios-sim could run smoothly on another Yosemite, thus I suspect it's related to local environment ( I had some issue with /usr/bin/xcrun ), I'll reinstall OS and try again.

**Comment by illusionhunter** [comment]
I've reinstalled OS, xcode and ios-sim, now it works fine. This is a system issue.
