### ISSUE TITLE
ios-sim fails to build windows 7

### ISSUE THREAD

**Issue by vishsid73** [phonegap/ios-sim#152]
Hi,
I am new to phonegap.
Have installed phonegap and while trying to npm install -g ios-sim, I was getting error of rake: 
    rake unrecognized internal or external command
so I installed ruby from rubyintsaller.org. After that I am getting this error:

    C:\Users\sidInfollion>npm install -g ios-sim
    xcodebuild clean -project ios-sim.xcodeproj
    rake aborted!
    Command failed with status (127): [xcodebuild clean -project ios-sim.xcodepro...
    ]
    C:/Users/sidInfollion/AppData/Roaming/npm/node_modules/ios-sim/Rakefile:12:in `b
    lock in <top (required)>'
    Tasks: TOP => build
    (See full trace by running task with --trace)

    npm ERR! ios-sim@3.1.1 preinstall: `rake build`
    npm ERR! Exit status 1
    npm ERR!
    npm ERR! Failed at the ios-sim@3.1.1 preinstall script.
    npm ERR! This is most likely a problem with the ios-sim package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     rake build
    npm ERR! You can get their info via:
    npm ERR!     npm owner ls ios-sim
    npm ERR! There is likely additional logging output above.
    npm ERR! System Windows_NT 6.1.7601
    npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nod
    ejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "ios-sim"
    npm ERR! cwd C:\Users\sidInfollion
    npm ERR! node -v v0.10.35
    npm ERR! npm -v 1.4.28
    npm ERR! code ELIFECYCLE
    npm ERR! not ok code 0

Please guide how to solve this.

**Comment by shazron** [comment]
It's only for OS X

**Comment by vishsid73** [comment]
@shazron 
Ok. Thanks. 
Please let me know is it possible to have an ios simulator on windows?

**Comment by shazron** [comment]
No.
