### ISSUE TITLE
Rake Build Fails

### ISSUE THREAD

**Issue by sineo** [phonegap/ios-sim#166]
npm install -g ios-sim
/Users/sineo/.rvm/bin/ruby: line 6: /Users/sineo/.rvm/bin/ruby: Argument list too long
/Users/sineo/.rvm/bin/ruby: line 6: /Users/sineo/.rvm/bin/ruby: Undefined error: 0
npm ERR! Darwin 13.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "ios-sim"
npm ERR! node v0.12.4
npm ERR! npm  v2.10.1
npm ERR! code ELIFECYCLE

npm ERR! ios-sim@3.1.1 preinstall: `rake build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ios-sim@3.1.1 preinstall script 'rake build'.
npm ERR! This is most likely a problem with the ios-sim package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     rake build
npm ERR! You can get their info via:
npm ERR!     npm owner ls ios-sim
npm ERR! There is likely additional logging output above.

**Comment by shazron** [comment]
what's your ruby version?
Also, diag info from here required: https://github.com/phonegap/ios-sim/blob/master/CONTRIBUTING.md

**Comment by sineo** [comment]
Hi,
Thanks for the response, I managed to get everything up and running by 
reinstalling everything and it just seemed to work this time.

Shazron Abdullah wrote:
