### ISSUE TITLE
devicetypeid is not defined

### ISSUE THREAD

**Issue by mhoffmeyerDC** [phonegap/ios-sim#175]
Although 3.2.0 (or 4.1.1) are the latest stable releases, running `npm i ios-sim` will install the latest release (5.0.0)... which doesn't seem to be working.

I couldn't get ios-sim launch ... to run, kept getting the error 'devicetypeid is not defined'

Also breaks ionic if doing a fresh install.

Cordova CLI: 5.2.0
Gulp version:  CLI version 3.9.0
Gulp local:
Ionic Version: 1.1.0
Ionic CLI Version: 1.6.4
Ionic App Lib Version: 0.3.8
ios-deploy version: 1.7.0
ios-sim version: 5.0.0
OS: Mac OS X Yosemite
Node Version: v0.12.7
Xcode version: Xcode 7.0 Build version 7A152u

**Comment by shazron** [comment]
@macdonst if you have time can you take a look.

**Comment by shazron** [comment]
if you find the problem, maybe we need to dist-tag 'latest' to the previous version/

**Comment by macdonst** [comment]
@mhoffmeyerDC can you give me the exact command you use to do ios-sim launch?

**Comment by mhoffmeyerDC** [comment]
Tried using just ionic command, `ionic emulate ios` and also directly with `ios-sim launch /path/to/app.app` Tried vaious permutations of --devicetypeid - all gave same result.

**Comment by macdonst** [comment]
@mhoffmeyerDC I just published 5.0.1. Please close this issue if it fixes it for you. If not, let us know.

**Comment by mhoffmeyerDC** [comment]
That did the trick. Thank you!

**Comment by joshbuchea** [comment]
Was seeing the same issue. Updating to 5.0.1 resolved it for me also. Thanks!
