### ISSUE TITLE
Black screen when starting iOS simulator as root

### ISSUE THREAD

**Issue by ionut-movila** [phonegap/ios-sim#178]
Command I have used, to start iPad 2 simulator for instance:

sudo ios-sim start --devicetypeid $(ios-sim showdevicetypes | grep iPad-2)

Same command if I run without sudo in front will start the simulator with no problems.

Running on OS X 10.10.5, with Xcode 7.0 and iOS SDK 9.0. 
Other info:
xcodebuild: Build version 7A220
xcrun: xcrun version 26.

I have installed ios-sim as root using:
"sudo npm install ios-sim -g"

**Comment by ionut-movila** [comment]
Looks like this is somehow related to either Xcode 7 or OS X 10.10.5, because on an older system with OS X 10.9.5, Xcode 6.2 and xcrun version 23 works fine.

**Comment by shazron** [comment]
Possibly related to #185

**Comment by shazron** [comment]
Re-open if you have any more info regarding this.
