### ISSUE TITLE
Black screen with Xcode 7

### ISSUE THREAD

**Issue by marekkalnik** [phonegap/ios-sim#185]
The dependency `simctl` uses the "iOS Simulator" command to launch the Simulator. This executable has been renamed to "Simulator" in Xcode 7 and it is no longer possible to deploy to simulator.

I have created a pull-request in https://github.com/phonegap/simctl/pull/7 an `ios-sim` should be updated accordingly when it is merged.

**Comment by shazron** [comment]
Thank you! The simctl pr has been merged and published, and dep change made here: https://github.com/phonegap/ios-sim/commit/fe08555f33597a5c6b2c1713cde68fe62a6023f7
