### ISSUE TITLE
Fails with targets of "iPhone-6s, 9.2" and "iPhone-6s-Plus, 9.2"

### ISSUE THREAD

**Issue by martinjbaker** [phonegap/ios-sim#186]
I've done `ios-sim showdevicetypes` and get the following

iPhone-4s, 8.4
iPhone-5, 8.4
iPhone-5s, 8.4
iPhone-6, 8.4
iPhone-6-Plus, 8.4
iPad-2, 8.4
iPad-Retina, 8.4
iPad-Air, 8.4
iPhone-4s, 9.2
iPhone-5, 9.2
iPhone-5s, 9.2
iPhone-6, 9.2
iPhone-6-Plus, 9.2
iPhone-6s, 9.2
iPhone-6s-Plus, 9.2
iPad-2, 9.2
iPad-Retina, 9.2
iPad-Air, 9.2
iPad-Air-2, 9.2
iPad-Pro, 9.2

but if I set the target to `iPhone-6s, 9.2` or `iPhone-6s-Plus, 9.2` then it fails with 
not a valid target for emulator
Other targets work fine.

**Comment by shazron** [comment]
I believe this is a Cordova iOS issue - this has been fixed https://github.com/apache/cordova-ios/commit/07fd9379872b949ce651efb9c4988b3d0bbb1b94
It should be out in the next platform release (> 4.0.1)
