### ISSUE TITLE
"Invalid device state" error using ios-sim 5.0.6, not when using 5.0.4

### ISSUE THREAD

**Issue by MSLaguana** [phonegap/ios-sim#187]
When I try to run the latest ios-sim to launch a particular app on a given simulator, I get an error:

    >/ios-sim launch path/to/my.app/ --devicetypeid iPhone-6s --exit
    An error was encountered processing the command (domain=com.apple.CoreSimulator.SimError, code=159):
    Invalid device state

If I don't specify a `devicetypeid` then it prints out the error twice, presumably because it is trying to target a simulator with a watch associated with it.

sw_vers: 10.11
ios-sim: 5.0.6
xcodebuild: Xcode 7.0.1, Build version 7A1001
xcode-select: /Applications/Xcode.app/Contents/Developer
gcc: ```Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/c++/4.2.1
Apple LLVM version 7.0.0 (clang-700.0.72)
Target: x86_64-apple-darwin15.0.0
Thread model: posix```

**Comment by shazron** [comment]
Could you try `Xcode 7.2`?

**Comment by shazron** [comment]
Some ideas here in the first few results: https://www.google.com/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=ios%20simulator%20invalid%20device%20state

**Comment by MSLaguana** [comment]
I don't want to change the state of this machine too much since I use it for testing things out. However I have another machine that repro'd the issue which was running xcode 7.2 already. Same arguments and result, and here's the machine info:

sw_vers: 10.10.5 BuildVersion: 14F1509
ios-sim: 5.0.6
xcodebuild Xcode 7.2, Build Version 7C68
xcode-select: /Applications/Xcode.app/Contents/Developer
gcc: ``` Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
 Apple LLVM version 7.0.2 (clang-700.1.81)
 Target: x86_64-apple-darwin14.5.0
 Thread model: posix ```

**Comment by shazron** [comment]
Might have to reset/validate your simulators - from the link I gave above: http://stackoverflow.com/a/32054924/219684

**Comment by joshuaskelton** [comment]
Looking further into this, I can consistently repro this issue with the following:

1. Launch your app `ios-sim launch Test.app --devicetypeid=iPhone-4s`
2. Wait for the simulator to start and app to launch. Leave the simulator running.
3. Launch your app again `ios-sim launch Test.app --devicetypeid=iPhone-5s`
4. Observe error:

`An error was encountered processing the command (domain=com.apple.CoreSimulator.SimError, code=159):`

I've verified that 5.0.4 correctly handles this scenario. Do you have any suggested workarounds?

**Comment by shazron** [comment]
Use the 5.0.7 release
