### ISSUE TITLE
ios-sim v5.0.6 always launch iPadAir regardless of devicetypeid

### ISSUE THREAD

**Issue by raymondleung416** [phonegap/ios-sim#188]
MacOS: 10.11.3 (on MacBookPro Mid 2014, Intel Core i7 2.2G)
XCode: 7.2.1

The following command should start iPhone-6s simulator, but iPadAir simulator came up.
> ios-sim start --devicetypeid "iPhone-6s"

I tried a few other device types, the iPadAir simulator always come up instead of the expected one.
This also happens with v5.0.5, but v5.0.4 works as expected (i.e. the iPhone 6s simulator comes up).

There is no error message on the terminal.

**Comment by shazron** [comment]
I just tried with 5.0.6, it works as expected -- uses the appropriate device that I specify each time.

**Comment by raymondleung416** [comment]
I did some digging and found my system is a little bit strange with regard to Xcode. I originally have Xcode 6 installed in /Applications. At some point, I renamed /Applications/Xcode.app to /Applications/Xcode6.app and then installed Xcode 7 beta as /Applications/Xcode.app. Since then I have upgraded it to the latest Xcode7. However, I still have /Applications/Xcode6.app there.

And I found that I have the following:
> ls -las /Applications/Xcode.app/Contents/Developer/Applications/
total 0
0 drwxr-xr-x   5 root  wheel   170B  5 Feb 17:35 ./
0 drwxr-xr-x  10 root  wheel   340B  5 Feb 17:37 ../
0 drwxr-xr-x   3 root  wheel   102B  5 Feb 17:45 DesktopReplayer.app/
0 drwxr-xr-x   3 root  wheel   102B  5 Feb 17:45 Simulator (Watch).app/
0 drwxr-xr-x   3 root  wheel   102B  5 Feb 17:45 Simulator.app/

> ls -las /Applications/Xcode6.app/Contents/Developer/Applications/
total 0
0 drwxr-xr-x   3 root  wheel   102B 20 Jun  2015 ./
0 drwxr-xr-x  11 root  wheel   374B 22 Jun  2015 ../
0 drwxrwxr-x   3 root  wheel   102B 27 Jul  2015 iOS Simulator.app/

So, somehow my iOS simulator is still under the Xcode6.app. I have verified that when the iPhone simulator is running, it is the simulator app under the Xcode6.app folder running. I did a "ps -ae" and find it in the output.

For some reason, ios-sim v5.0.4 is able to find that iOS simulator but not v5.0.5 and above.

**Comment by raymondleung416** [comment]
ios-sim v5.0.6 now runs fine after I removed the old simulator.

**Comment by shazron** [comment]
Yeah unfortunately it tries to launch the old simulator first if available, then uses the new. If you only had Xcode 7, it would be fine.

https://github.com/phonegap/simctl/commit/2d26515d7397fe04ab4a9c58117e6e6fbcd9356d

**Comment by raymondleung416** [comment]
Maybe it should try launching the "Simulator" from Xcode 7 first and if that fails, try launching the "IOS Simulator" from Xcode 6?

**Comment by shazron** [comment]
Yes, this is better. Slating for 5.1.0

**Comment by shazron** [comment]
Try the 5.0.7 release.

**Comment by shazron** [comment]
Closing since it should be fixed in 5.0.7+
