### ISSUE TITLE
Info.plist file not found.

### ISSUE THREAD

**Issue by mikecastrodemaria** [phonegap/ios-sim#195]
Hi,

`I'm using ios-sim launch ./platforms/ios/ --log use.log
`
And get Info.plist file not found.

I did not have Info.plist when I build, juste a project-Info.plist, is it the good file ? How use it ?
Thanks

**Comment by shazron** [comment]
Actually, you are using it incorrectly. You need to specify the path to the .app file (for the Simulator) itself.

**Comment by pixelass** [comment]
I think this library deserves a better documentation. I usage is anything but intuitive.
