### ISSUE TITLE
ios simulator doesn't work anymore with Xcode 8

### ISSUE THREAD

**Issue by moletteg** [phonegap/ios-sim#196]
Hello everyone;
I encounter an issue when i launch the ios -simulator on Xcode.
The simulator doesn't open anymore and i get the error message : "Failed to find class DTiPhoneSimulatorSystemRoot at runtime."
Do you guys know what i have to do to fix this problem ? 
thanks for your help.

**Comment by luciocosmo** [comment]
Same problems in our project. We're following conversation waiting a fix.

**Comment by einsty** [comment]
This may not be for everyone, but, I re-installed ios-sim with `sudo npm i ios-sim -g`.  It complained about there already being software at the location and to move it out of the way... I did, and then re-ran the install and that resolved my issue...

**Comment by SuyashLakhotia** [comment]
+1

**Comment by christophermiles** [comment]
+1

**Comment by Overload119** [comment]
@einsty trick worked, also it seems you have to specify the devicetype ID now,

`ios-sim start --devicetypeid iPhone-5s` should do the trick.

**Comment by shazron** [comment]
When you launch `ios-sim start` it should put out a warning that you did not specify `devicetypeid` (ios-sim 5.0.8)

**Comment by MayankLogiciel** [comment]
I updated ios-sim version to 5.0.13(latest) and everything started working 

Step 1 : `sudo npm install -g ios-sim `

Step 2:` ios-sim launch YourApp.app --devicetypeid iPhone-5s`

**Comment by LeonXtp** [comment]
@MayankLogiciel your answer works fine!
