### ISSUE TITLE
How can I use ios-sim without node.js environment

### ISSUE THREAD

**Issue by natural-law** [phonegap/ios-sim#199]
I can generate ios-sim as a binary executable file with 3.0 & earlier versions. But now the ios-sim source code is implemented by node.js. Could you show me how can I use ios-sim without node.js environment? Such as a binary executable file or anything else without node.js.

Would appreciate any feedback / help....Thanks for your time and God Bless....

**Comment by shazron** [comment]
I'm afraid you can't. ios-sim is now a wrapper for the `simctl` utility that comes with xcode, and the wrapper is written in node.js. Sorry :(
