### ISSUE TITLE
no more need autocomplete com.apple.CoreSimulator.SimDeviceType. in xcode 8.1

### ISSUE THREAD

**Issue by neuberfran** [phonegap/ios-sim#204]
sh-3.2# ios-sim launch platforms/ios/build/emulator/Best\ Reader\ Ever.app  --devicetypeid iPhone-7-plus, 10.1
Device type "com.apple.CoreSimulator.SimDeviceType.iPhone-7-plus" could not be found.

sh-3.2# ionic info

Your system information:

Cordova CLI: 6.4.0 
Ionic Framework Version: 2.0.0-rc.3
Ionic CLI Version: 2.1.17
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.45
ios-deploy version: 1.9.0 
ios-sim version: 5.0.13 
OS: macOS Sierra
Node Version: v7.2.1
Xcode version: Xcode 8.1 Build version 8B62

sh-3.2# ios-sim showdevicetypes
iPhone-7, 10.1
iPhone-7-Plus, 10.1
Apple-TV-1080p, tvOS 10.0
Apple-Watch-38mm, watchOS 2.2
Apple-Watch-38mm, watchOS 3.1

**Comment by shazron** [comment]
I can't repro. I only test with Cordova. It's up to you if you have Ionic issues.

I tried, and it was successful:
```
ios-sim launch platforms/ios/build/emulator/HelloCordova.app --devicetypeid "iPhone-7-Plus, 10.2"
```

My env:
```
$ cordova --version
6.4.0
$ cordova platform ls
Installed platforms:
  ios 4.3.1
$ xcodebuild -version
Xcode 8.2
Build version 8C38
$ ios-sim --version
5.0.13
$ ios-sim showdevicetypes
iPhone-4s, 8.2
iPhone-4s, 8.4
iPhone-5, 8.2
iPhone-5, 8.4
iPhone-5, 10.2
iPhone-5s, 8.2
iPhone-5s, 8.4
iPhone-5s, 10.2
iPad-2, 8.2
iPad-2, 8.4
iPad-Retina, 8.2
iPad-Retina, 8.4
iPad-Retina, 10.2
iPad-Air, 8.2
iPad-Air, 8.4
iPad-Air, 10.2
iPhone-6, 8.2
iPhone-6, 8.4
iPhone-6, 10.2
iPhone-6-Plus, 8.2
iPhone-6-Plus, 8.4
iPhone-6-Plus, 10.2
iPhone-6s, 10.2
iPhone-6s-Plus, 10.2
iPhone-7, 10.2
iPhone-7-Plus, 10.2
iPhone-SE, 10.2
iPad-Air-2, 10.2
iPad-Pro--9-7-inch-, 10.2
iPad-Pro, 10.2
Apple-TV-1080p, tvOS 10.1
Apple-Watch-38mm, watchOS 3.1
Apple-Watch-42mm, watchOS 3.1
Apple-Watch-Series-2-38mm, watchOS 3.1
Apple-Watch-Series-2-42mm, watchOS 3.1
```

**Comment by neuberfran** [comment]
![captura de tela 2016-12-17 as 17 21 09](https://cloud.githubusercontent.com/assets/7308528/21290802/40f38f8a-c47d-11e6-98f1-048171fc1766.png)
ok. But NOW I have a old issue with ionic 2
https://forum.ionicframework.com/t/error-enoent-no-such-file-or-directory-stat-var-root-library-logs-coresimulator-1a2f74cf-a3f0-422e-bdb0-9188409f7529-system-log/72775/3

**Comment by neuberfran** [comment]
Anyone ?

**Comment by shazron** [comment]
Seems to be an Ionic issue to be reported on their forums, and no repro as stated above.
