### ISSUE TITLE
TypeError: Cannot read property 'replace' of undefined (lib.js:282)

### ISSUE THREAD

**Issue by JedatKinports** [phonegap/ios-sim#210]
The **command line arguments** i used for ios-sim:

./platforms/ios/cordova/lib/list-emulator-images

# Expected behavior

Get a list of simulators.

# Actual behavior.

TypeError: Cannot read property 'replace' of undefined in ios-sim/src/lib.js:282

# Steps to reproduce the problem

Run "./platforms/ios/cordova/lib/list-emulator-images" in your cordova project.

# System Specs

Please run the commands below in your Terminal.app and include it in the issue. Check when done and include results below.

- [x] 1. system_profiler SPSoftwareDataType

System Software Overview:

      System Version: macOS 10.12.5 (16F73)
      Kernel Version: Darwin 16.6.0
      Boot Volume: macOS
      Boot Mode: Normal
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled

- [x] 2. ios-sim --version

5.0.12

- [x] 3. xcodebuild -version

Xcode 8.3.3
Build version 8E3004b

- [x] 4. xcode-select --print-path

/Applications/Xcode.app/Contents/Developer

- [x] 5. node --version

v7.10.0

# My solution

The solution for myself, because i don't need the "iPad Pro (10.5-inch)" simulator if it even works (who knows):

The problem is that the `name_id_map[deviceName]` returns `undefined` for "**iPad Pro (12.9-inch)**" and "**iPad Pro (10.5-inch)**".

I fixed this bug by adding an if statements which checks if the device is defined in "**platforms/ios/cordova/node_modules/ios-sim/src/lib.js:282**".

I replaced this:

```
    list = [];
            var remove = function(runtime) {
                // remove "iOS" prefix in runtime, remove prefix "com.apple.CoreSimulator.SimDeviceType." in id
                list.push(util.format('%s, %s', name_id_map[ deviceName ].replace(/^com.apple.CoreSimulator.SimDeviceType./, ''), runtime.replace(/^iOS /, '')));
            };
```

with this:

```
    list = [];
            var remove = function(runtime) {
                // remove "iOS" prefix in runtime, remove prefix "com.apple.CoreSimulator.SimDeviceType." in id
                if (name_id_map[deviceName] && runtime) {
                    list.push(util.format('%s, %s', name_id_map[deviceName].replace(/^com.apple.CoreSimulator.SimDeviceType./, ''), runtime.replace(/^iOS /, '')));
                }
            };
```

Link to the issue on stackoverflow: https://stackoverflow.com/a/44451292/7199922

**Comment by piotrowski** [comment]
There already is a ios-sim version `5.0.13`. Does updating to this version (`npm i -g ios-sim`) fix the problem?

**Comment by JedatKinports** [comment]
@piotrowski no. The error is still there. After the update to 5.1.0 with `npm i -g ios-sim` i still get the error.

**Comment by piotrowski** [comment]
Hm, maybe ios-sim is installed locally additionally? Then maybe try removing it.

(I'm trying to help people debug similar problems with Ionic, which uses Cordova under the hood: https://forum.ionicframework.com/t/error-cannot-read-property-replace-of-undefined/93297)

**Comment by JedatKinports** [comment]
I removed the ios-sim directory inside myApp/platforms/ios/cordova/node_modules and now it's working. Now it uses the global installed one i guess. Thanks! :)

**Comment by theHellyar** [comment]
@JedatKinports this worked for me thanks!

**Comment by piotrowski** [comment]
If anyone is wondering where the "local" ios-sim comes from and couldn't find the `package.json` locally:
https://github.com/apache/cordova-ios/blob/master/package.json#L49

**Comment by shazron** [comment]
@JedatKinports in your project folder root, do `cd platforms/ios/cordova && npm install ios-sim`

**Comment by shazron** [comment]
I'm closing this issue since it has actually been fixed in ios-sim. The workarounds for Cordova have also been shown.

**Comment by piotrowski** [comment]
Is there a way to properly fix this in newly created projects? Ionic for example tends to treat everything in `/platforms` as disposable, so some people might get this problem over and over again...

**Comment by shazron** [comment]
@piotrowski no. Ionic if they use cordova templates for project generation could add a hook or something.

**Comment by shazron** [comment]
I'll try to get a cordova-ios platform release patch out soonest.

**Comment by piotrowski** [comment]
@shazron Thank you. I will keep posting our workaround for now. At least we know how to fix it now, so 🥇

**Comment by JedatKinports** [comment]
@shazron platforms/ios/cordova/package.json doesn't exists. And there is only a node_modules directory not .node_modules. don't know if that matters. Doesn't matter as long as this fix works. Was just curious. ;)

**Comment by shazron** [comment]
In the meantime, I cherry-picked the ios-sim fix only and applied it to cordova-ios@4.4.0
To use:
`cordova platform add https://github.com/apache/cordova-ios.git#4.4.0-ios-sim`

**Comment by anuragsoftware** [comment]
cd platforms/ios/cordova/node_modules/
sudo npm install ios-sim@latest

**Comment by JedatKinports** [comment]
@anuragsoftware i tried that also, didn't work.

**Comment by CodelessFuture** [comment]
sudo npm install ios-sim@5.0.12 works

**Comment by howardowens** [comment]
new to using the simulator ... trying it for the first time tonight.  The solution offered by anuragsoftware worked for me.

**Comment by renatoalencar** [comment]
It worked for me:

```cd platforms/ios/cordova/ && npm install ios-sim&latest```

**Comment by jamesjara** [comment]
It works `cd platforms/ios/cordova/ && npm install ios-sim&latest` or selecting a device

**Comment by mesqueeb** [comment]
This solved my problem as well!!! Thanks so much @JedatKinports !!!

**Comment by JedatKinports** [comment]
@mesqueeb you are welcome. :)

**Comment by kouskefil** [comment]
Hi everyone, i'm begining with ionic and i get the same problem but with android. I would appreciate your helps. thanks in advance

**Comment by JedatKinports** [comment]
@kouskefil what kind of error do you get? I don't think that it's the exact same one. If it's not the same then i would suggest that you open a new issue.

**Comment by kouskefil** [comment]
TypeError: Cannot read property 'replace' of undefined was the error, now I do reinstall android studio and everything works fine.  thanks

**Comment by beesden** [comment]
We added a simple hook for our build process:

**config.xml**
`<hook src="hooks/update-ios-sim.js" type="before_deploy" />`


**hooks/update-ios-sim.js**
```
#!/usr/bin/env node
const fs = require('fs');
const execSync = require('child_process').execSync;

if (fs.existsSync('platforms/ios')) {
  execSync('cd platforms/ios/cordova && npm install ios-sim@latest');
}
```

**Comment by fabiancook** [comment]
I resolved this issue by updating ios-sim on my global cordova install rather than local.

**Comment by prescottprue** [comment]
Got it working with `cd platforms/ios/cordova/ && npm install ios-sim@latest && cd ....` (notice the `&` is replaced with `@`, and the final cd brings you back)

@beesden , I like your idea. Might try that out.
