### ISSUE TITLE
Device Type ignored when Simulator Already Running

### ISSUE THREAD

**Issue by rhgills** [phonegap/ios-sim#49]
When specifying a specific device to launch with, an already running simulator will be used regardless of if that simulator's device is different than the specified device.

To reproduce (on ios-sim version 1.7):

1. quit the simulator
2. `ios-sim launch --family 'ipad' app/path`
3. DON'T quit the simulator
4. `ios-sim launch --family 'iphone' app/path`

The app will be launched inside the already running iPad simulator, instead of in an iPhone simulator. To workaround, you need to quit the simulator whenever you want to launch with a device type that isn't that of the currently running simulator.

See also: https://github.com/moredip/Sim-Launcher/issues/20

**Comment by shazron** [comment]
With the --devicetypeid option (in 3.x), this shouldn't be a problem anymore.
