### ISSUE TITLE
Use simctl (Xcode 6)

### ISSUE THREAD

**Issue by shazron** [phonegap/ios-sim#92]
$ xcrun simctl
WARNING: The simctl interface is not stable and is likely to change prior to release.
Usage: simctl [--noxpc] [--set <set path>] <subcommand> ... | help [subcommand]
Command line utility to control the iOS Simulator

Subcommands:
	create      Create a new device.
	delete      Delete a device.
	erase       Erase a device's contents and settings.
	boot        Boot a device.
	shutdown    Shutdown a device.
	rename      Rename a device.
	getenv      Print an environment variable from a running device.
	openurl     Open a URL in a given SimDevice
	addphoto    Add photo to the photo library of a given SimDevice
	launch      Launch an application by identifier
	spawn       Spawn a process in the simulator
	list        List available sessions, devices, or runtimes.
	help        Prints the usage for a given subcommand.

**Comment by shazron** [comment]
Changes are logged in the "Usage" in the README as development progresses: https://github.com/phonegap/ios-sim/tree/4.x#usage

**Comment by taren7** [comment]
I am trying to use simctl to erase content and settings. It gives me an error saying 
"An error was encountered processing the command (code=146):
Unable to erase contents and settings in current state: Booted"

Any idea how to fix this?

**Comment by shazron** [comment]
Are you using the simctl node module or using simctl directly? If it's an issue for the node module, file an issue here instead: https://github.com/phonegap/simctl/issues

**Comment by taren7** [comment]
I am using simctl directly
On May 28, 2015 11:51 PM, "Shazron Abdullah" <notifications@github.com>
wrote:
>
> Are you using the simctl node module or using simctl directly? If it's an
issue for the node module, file an issue here instead:
https://github.com/phonegap/simctl/issues

**Comment by shazron** [comment]
Then your issue is off-topic for this thread or phonegap/simctl. If I knew the answer I would reply but I don't unfortunately.
